drop table suser;

SELECT *
FROM USER_CONSTRAINTS
WHERE R_CONSTRAINT_NAME IN (
SELECT CONSTRAINT_NAME
FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'SUSER'
AND CONSTRAINT_TYPE IN ('P', 'U')
)
AND CONSTRAINT_TYPE = 'R';

ALTER TABLE sorder
DROP CONSTRAINT ORDER_USER_FK;

drop table paytype;
